baseURL = 'https://davidtakac.github.io/'
languageCode = 'en-us'
title = "David's Website"
theme = 'PaperMod'

[params]
    showreadingtime = true
    showcodecopybuttons = true
    defaulttheme = 'auto'

[params.homeInfoParams]
    title = "Hello ğŸ‘‹"
    content = "I am David TakaÄ and this is my website. Here you can find my thoughts on Android development and anything else I find interesting. Welcome!"

[[params.socialIcons]]
    name = 'github'
    url = "https://www.github.com/davidtakac/"

[[params.socialIcons]]
    name = 'linkedin'
    url = "https://linkedin.com/in/davidtakac/"

[menu]
[[menu.main]]
    name = "Tags"
    pageRef = "/tags"