baseURL = 'https://davidtakac.github.io/'
languageCode = 'en-us'
title = "David's Website"
theme='PaperMod'
sectionPagesMenu = 'main'

[params.homeInfoParams]
    title = "Hello ğŸ‘‹"
    content = "I am David TakaÄ and this is my website. Here, you can find my thoughts on Android development and anything else I may wish to write about. You can also see more about me in the About section. Welcome, and I hope you enjoy your stay."

[[params.socialIcons]]
    name = 'github'
    url = "https://www.github.com/davidtakac/"

[[params.socialIcons]]
    name = 'linkedin'
    url = "https://linkedin.com/in/davidtakac/"